/**
 * All the threads that the admin will need to work with
 */

export const TEST_GRAPH_THREAD = "TEST_GRAPH_THREAD";

export const TEST_GRAPH_THREAD_TWO = "TEST_GRAPH_THREAD_TWO";

export const GET_ALL_CLIENTS_THREAD = "GET_ALL_CLIENTS_THREAD";

export const GET_HOME_THREAD = "GET_HOME_THREAD";

export const GET_ALL_CATEGORIES_THREAD = "GET_ALL_CATEGORIES_THREAD";

export const GET_CATEGORY_THREAD = "GET_CATEGORY_THREAD";

export const CUSTOMER_SIGN_UP_THREAD = "CUSTOMER_SIGN_UP_THREAD";

export const CUSTOMER_LOGIN_THREAD = "CUSTOMER_LOGIN_THREAD";

export const CUSTOMER_LOGOUT_THREAD = "CUSTOMER_LOGOUT_THREAD";

export const GET_PRODUCT_DETAILS_THREAD = 'GET_PRODUCT_DETAILS_THREAD';

export const GET_PRODUCTS_BY_CATEGORY_THREAD = 'GET_PRODUCT_BY_CATEGORY_THREAD';

