mutation ClientCreateAccount($name: String! $email: String! $phoneNumber: String! $password: String) {
    clientCreateAccount(name: $name, email: $email, phoneNumber: $phoneNumber, password: $password)
}