/**Blog Action types */
export const BLOG_POSTS = 'BLOG_POSTS';
export const GET_BLOG_POSTS = 'GET_BLOG_POSTS';
export const GET_BLOG_POSTS_STARTED = "GET_BLOG_POSTS_STARTED";
export const GET_BLOG_POSTS_FAILED = 'GET_BLOG_POSTS_FAILED';
export const GET_BLOG_POSTS_SUCCESS = 'GET_BLOG_POSTS_SUCCESS';
export const GET_BLOG_POSTS_INITAL_LOAD = 'GET_BLOG_POSTS_INITAL_LOAD';
export const GO_TO_NEXT_PAGE =  'GO_TO_NEXT_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
export const NEXT_PAGE_ERORR = 'NEXT_PAGE_ERROR'
export const NEXT_PAGE_SUCCESS = 'NEXT_PAGE_SUCCESS'
export const INITIAL_BLOG_POSTS_LOAD = 'INITAL_BLOG_POSTS_LOAD'
export const GET_BLOG_POSTS_NETWORK_ERROR =  'GET_BLOG_POSTS_NETWORK_ERROR'
export const LOAD_MORE_POSTS = 'LOAD_MORE_POSTS'
export const GET_BLOG_POSTS_COMPLETED =  'GET_BLOG_POSTS_COMPLETED';

/**
 * Read Blog Post 
 */
export const READ_BLOG_POST_INITAIL_LOAD = 'READ_BLOG_POST_INITAIL_LOAD'
export const READ_BLOG_POST_LOADED = 'READ_BLOG_POST_LOADED'
export const READ_BLOG_POST_FETCH_STARTED = 'READ_BLOG_POST_FETCH_STARTED'
export const READ_BLOG_POST_FETCH_SUCCESS = 'READ_BLOG_POST_FETCH_SUCCESS'
export const READ_BLOG_POST_FETCH_NETWORK_ERROR = 'READ_BLOG_POST_NETWORK_ERROR'
export const READ_BLOG_POST_FETCH_FAILED = 'READ_BLOG_POST_FETCH_FAILED'
export const READ_BLOG_POST_NOT_FOUND = 'READ_BLOG_POST_NOT_FOUND'



/**
 * General cactions
 */ 
export const REQUEST_STARTED = "SENDING_STARTED";
export const REQUEST_FAILED = "SENDING_FAILED";
export const REQUEST_COMPLETED = "SENDING_COMPLETED";
export const REQUEST_VALIDATION_ERROR = "SENDING_VALIDATION_ERROR";
export const REQUEST_NETWORK_ERROR = "REQUEST_NETWORK_ERROR";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_ALL_LOADED = "REQUEST_ALL_LOADED";
export const REQUEST_PENDING = "REQUEST_PENDING";
export const REQUEST_SERVER_ERROR = "REQUEST_SERVER_ERROR";
export const REQUEST_TIMEOUT = "REQUEST_TIMEOUT";
export const REQUEST_RETRY_SUCCESS = "REQUEST_RETRY_SUCCESS";

export const ITEM_NOT_FOUND = "ITEM_NOT_FOUND";

export const RELOAD_CONTENT = "RELOAD_CONTENT";

export const READ_TOPIC = "READ_TOPIC";

export const NOT_FOUND = "NOT_FOUND";

export const IS_EDITING = "IS_EDITING";

export const CLEAR_DATA_FROM_THREAD = 'CLEAR_DATA_FROM_THREAD';
